--liquibase formatted sql

--changeset albanyqq:1

CREATE TABLE `TEST_TABLE` (`ID` BIGINT(20) AUTO_INCREMENT  NOT NULL, `CODE` VARCHAR(20) NOT NULL, `DESCRIPTION` VARCHAR(200), `VALUE` VARCHAR(200), CONSTRAINT `PK_TEST_TABLE` PRIMARY KEY (`ID`), UNIQUE (`CODE`));

ALTER TABLE `TEST_TABLE` ADD CONSTRAINT `CODE_UK` UNIQUE (`CODE`, `DESCRIPTION`);

CREATE TABLE `ANOTHER_TEST_TABLE` (`ID` BIGINT(20) AUTO_INCREMENT  NOT NULL, `CODE` VARCHAR(20) NOT NULL, `TEST_CODE` VARCHAR(20), CONSTRAINT `PK_ANOTHER_TEST_TABLE` PRIMARY KEY (`ID`), UNIQUE (`CODE`));

ALTER TABLE `ANOTHER_TEST_TABLE` ADD CONSTRAINT `TEST_OTHER_FK` FOREIGN KEY (`TEST_CODE`) REFERENCES `TEST_TABLE` (`CODE`);